services:
  interface:
    build:
      context: interface
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SLURM_JWT: ${SLURM_JWT}
      SLURM_API_URL: ${SLURM_API_URL}
      CURRENT_USER: ${CURRENT_USER}
      LOG_LEVEL: ${LOG_LEVEL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      NEXT_LOCAL_KEYCLOAK_URL: ${NEXT_LOCAL_KEYCLOAK_URL}
      NEXT_PUBLIC_KEYCLOAK_REALM: ${NEXT_PUBLIC_KEYCLOAK_REALM}
      NEXT_CONTAINER_KEYCLOAK_ENDPOINT: ${NEXT_CONTAINER_KEYCLOAK_ENDPOINT}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    networks:
      - slurm-network
    ports:
      - "3000:3000"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.6
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    networks:
      - slurm-network
    ports:
      - "${KC_PORT}:8080"

networks:
  slurm-network:
