services:
  interface:
    build:
      context: interface
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SLURM_JWT: ${SLURM_JWT}
      SLURM_API_URL: ${SLURM_API_URL}
      CURRENT_USER: ${CURRENT_USER}
      LOG_LEVEL: ${LOG_LEVEL}
      KC_CLIENT_ID: ${KC_CLIENT_ID}
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
      KC_LOCAL_URL: ${KC_LOCAL_URL}
      KC_REALM: ${KC_REALM}
      KC_CONTAINER_HOSTNAME_URL: ${KC_CONTAINER_HOSTNAME_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    networks:
      - slurm-network
    ports:
      - "3000:3000"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.6
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    networks:
      - slurm-network
    ports:
      - "8080:8080"

networks:
  slurm-network:
    driver: bridge
