services:
  interface:
    build:
      context: interface
      dockerfile: Dockerfile
    restart: always
    environment:
      SLURM_JWT: ${SLURM_JWT}
      SLURM_API_URL: ${SLURM_API_URL}
      CURRENT_USER: ${CURRENT_USER}
      LOG_LEVEL: ${LOG_LEVEL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    networks:
      - slurm-network
    ports:
      - "127.0.0.1:3000:3000"

networks:
  slurm-network:
    driver: bridge
